recipe: default.v1
assistant_id: 20240110-074001-foggy-compressor
language: vi
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 10
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true



# pipeline:
#   - name: Vietnamese Tokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
# #  - name: CRFEntityExtractor
# #    name: EntitySynonymMapper
# name: CountVectors Featurizer
# analyzer: "char_wb"
# min_ngram: 1
# max_ngram: 4
# #name: FastTextFeaturizer
# #cache_dir: "/path/to/vectors/"
# #file: "cc.en.300.bin"
# #  - name: Printer
# #    alias: after fasttext
# #  - name: EmbeddingIntentClassifier
# #    batch_strategy: sequence

# name: rasa_nlu_examples.featurizers.dense.BytePairFeaturizer
# lang: vi
# vs: 200000
# dim: 300
# cache_dir: cmp/bpe/vi
# model_file: cmp/bpe/vi/vi.wiki.bpe.vs200000.model
# emb_file: cmp/bpe/vi/vi.wiki.bpe.vs200000.d300.w2v.bin
# name: rasa_nlu_examples.featurizers.dense.FastTextFeaturizer
# cache_dir: cmp/fasttext
# file: cc.vi.300.bin 
# name: DIETClassifier
# epochs: 100
# constrain_similarities: true
# model_confidence: linear_norm
# name: EntitySynonymMapper
# name: ResponseSelector
# epochs: 100
# name: FallbackClassifier
# threshold: 0.2